#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strategic.DataServices.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="ETF")]
	public partial class ETFDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void DeletePrice(Price instance);
    #endregion
		
		public ETFDataContext() : 
				base(global::Strategic.DataServices.Database.Properties.Settings.Default.ETFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ETFDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ETFDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ETFDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ETFDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Price> Prices
		{
			get
			{
				return this.GetTable<Price>();
			}
		}
		
		private void InsertPrice(Price obj)
		{
			System.Nullable<int> p1 = obj.Id;
			this.UpSert_ETFPrices(ref p1, obj.Symbol, ((System.Nullable<System.DateTime>)(obj.Date)), ((System.Nullable<decimal>)(obj.Open)), ((System.Nullable<decimal>)(obj.High)), ((System.Nullable<decimal>)(obj.Low)), ((System.Nullable<decimal>)(obj.Close)), ((System.Nullable<long>)(obj.Volume)), ((System.Nullable<decimal>)(obj.AdjustedClose)));
			obj.Id = p1.GetValueOrDefault();
		}
		
		private void UpdatePrice(Price obj)
		{
			System.Nullable<int> p1 = obj.Id;
			this.UpSert_ETFPrices(ref p1, obj.Symbol, ((System.Nullable<System.DateTime>)(obj.Date)), ((System.Nullable<decimal>)(obj.Open)), ((System.Nullable<decimal>)(obj.High)), ((System.Nullable<decimal>)(obj.Low)), ((System.Nullable<decimal>)(obj.Close)), ((System.Nullable<long>)(obj.Volume)), ((System.Nullable<decimal>)(obj.AdjustedClose)));
			obj.Id = p1.GetValueOrDefault();
		}
		
		[Function(Name="dbo.UpSert_ETFPrices")]
		public int UpSert_ETFPrices([Parameter(Name="PriceId", DbType="Int")] ref System.Nullable<int> priceId, [Parameter(Name="Symbol", DbType="NVarChar(5)")] string symbol, [Parameter(Name="Date", DbType="DateTime")] System.Nullable<System.DateTime> date, [Parameter(Name="Open", DbType="Decimal")] System.Nullable<decimal> open, [Parameter(Name="High", DbType="Decimal")] System.Nullable<decimal> high, [Parameter(Name="Low", DbType="Decimal")] System.Nullable<decimal> low, [Parameter(Name="Close", DbType="Decimal")] System.Nullable<decimal> close, [Parameter(Name="Volume", DbType="BigInt")] System.Nullable<long> volume, [Parameter(Name="AdjustedClose", DbType="Decimal")] System.Nullable<decimal> adjustedClose)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), priceId, symbol, date, open, high, low, close, volume, adjustedClose);
			priceId = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[Table(Name="dbo.Prices")]
	public partial class Price : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Symbol;
		
		private System.DateTime _Date;
		
		private decimal _Open;
		
		private decimal _High;
		
		private decimal _Low;
		
		private decimal _Close;
		
		private long _Volume;
		
		private System.Nullable<decimal> _AdjustedClose;
		
		private EntityRef<Price> _Price2;
		
		private EntityRef<Price> _Price1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSymbolChanging(string value);
    partial void OnSymbolChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnOpenChanging(decimal value);
    partial void OnOpenChanged();
    partial void OnHighChanging(decimal value);
    partial void OnHighChanged();
    partial void OnLowChanging(decimal value);
    partial void OnLowChanged();
    partial void OnCloseChanging(decimal value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(long value);
    partial void OnVolumeChanged();
    partial void OnAdjustedCloseChanging(System.Nullable<decimal> value);
    partial void OnAdjustedCloseChanged();
    #endregion
		
		public Price()
		{
			this._Price2 = default(EntityRef<Price>);
			this._Price1 = default(EntityRef<Price>);
			OnCreated();
		}
		
		[Column(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					if (this._Price1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_Symbol", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string Symbol
		{
			get
			{
				return this._Symbol;
			}
			set
			{
				if ((this._Symbol != value))
				{
					this.OnSymbolChanging(value);
					this.SendPropertyChanging();
					this._Symbol = value;
					this.SendPropertyChanged("Symbol");
					this.OnSymbolChanged();
				}
			}
		}
		
		[Column(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[Column(Name="[Open]", Storage="_Open", DbType="Decimal(18,4) NOT NULL")]
		public decimal Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[Column(Storage="_High", DbType="Decimal(18,4) NOT NULL")]
		public decimal High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[Column(Storage="_Low", DbType="Decimal(18,4) NOT NULL")]
		public decimal Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[Column(Name="[Close]", Storage="_Close", DbType="Decimal(18,4) NOT NULL")]
		public decimal Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[Column(Storage="_Volume", DbType="BigInt NOT NULL")]
		public long Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[Column(Storage="_AdjustedClose", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> AdjustedClose
		{
			get
			{
				return this._AdjustedClose;
			}
			set
			{
				if ((this._AdjustedClose != value))
				{
					this.OnAdjustedCloseChanging(value);
					this.SendPropertyChanging();
					this._AdjustedClose = value;
					this.SendPropertyChanged("AdjustedClose");
					this.OnAdjustedCloseChanged();
				}
			}
		}
		
		[Association(Name="Price_Price", Storage="_Price2", ThisKey="Id", IsUnique=true, IsForeignKey=false)]
		public Price Price2
		{
			get
			{
				return this._Price2.Entity;
			}
			set
			{
				Price previousValue = this._Price2.Entity;
				if (((previousValue != value) 
							|| (this._Price2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Price2.Entity = null;
						previousValue.Price1 = null;
					}
					this._Price2.Entity = value;
					if ((value != null))
					{
						value.Price1 = this;
					}
					this.SendPropertyChanged("Price2");
				}
			}
		}
		
		[Association(Name="Price_Price", Storage="_Price1", ThisKey="Id", IsForeignKey=true)]
		public Price Price1
		{
			get
			{
				return this._Price1.Entity;
			}
			set
			{
				Price previousValue = this._Price1.Entity;
				if (((previousValue != value) 
							|| (this._Price1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Price1.Entity = null;
						previousValue.Price2 = null;
					}
					this._Price1.Entity = value;
					if ((value != null))
					{
						value.Price2 = this;
						this._Id = value.Id;
					}
					else
					{
						this._Id = default(int);
					}
					this.SendPropertyChanged("Price1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
